config/routes.rb
Rails.application.routes.draw do
  root("pages#home")
  get("about", to: "pages#about")
  # posts/1/comments/3
  get("search", to: "search#index")
  resources(:posts) do
    resources :comments
  end
  get("users/profile")
  devise_for(:users, controllers: { sessions: "users/sessions", registrations: "users/registrations" })
  get("u/:id", to: "users#profile", as: "user")
end

app/models/post.rb
class Post < ApplicationRecord
  validates(:title, presence: true, length: { minimum: 5, maximum: 10 })
  validates(:body, presence: true, length: { minimum: 8, maximum: 50 })
  belongs_to(:user)
  has_many(:comments, dependent: :destroy)
  has_noticed_notifications(model_name: "Notification")
  has_many(:notifications, through: :user, dependent: :destroy)
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action(:set_post, only: %i[ show edit update destroy ])
  before_action(:authenticate_user!, except: %i[show index])

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
    views = @post.views + 1
    @post.views = views
    @post.save
    #  OR
    # @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc)

    mark_notifications_as_read()
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to(post_url(@post), notice: "This Post was successfully created.") }
        format.json { render(:show, status: :created, location: @post) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @post.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        # means
        # Post.update(id: params[:id], title: params[:title], body: params[:body])
        format.html { redirect_to(post_url(@post), notice: "Post was successfully updated.") }
        format.json { render(:show, status: :ok, location: @post) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @post.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url, notice: "Post was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end

  def mark_notifications_as_read
    if current_user
      notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
      notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <form>
    <div class="mb-3">
      <label class="form-label">Title</label>
       <%= form.text_field(:title, size: "22") %>
    </div>
    <div class="mb-3">
      <label class="form-label">Body</label>
       <%= form.text_area(:body, size: "25x5") %>
    </div>

    <%= form.submit("Create Post", class: "btn btn-success") %>
  </form>
  <% end %>

app/views/posts/_post.html.erb
    <h5 class="card-title"><%= post.title %></h5>
    <p> Posted By:  <%= link_to(post.user.name, user_path(post.user)) %> </p>
    <h6> <%= pluralize(post.views, "view") %></h6>
    <p class="card-text"><%= post.body %></p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render("form", post: @post) %>

<br>

<div>
  <%= link_to("Show this post", @post) %> |
  <%= link_to("Back to posts", posts_path) %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

  <div class=" d-flex  bd-highlight ">

    <div class="p-2 flex-fill  bd-highlight"> <h1>Posts</h1> </div>

    <div class="p-2 flex-fill   bd-highlight">

         <!---- Button trigger modal -->
          <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
            New Post
          </button>

          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content" >
                <div class="modal-header">
                  <h5 class="modal-title " id="exampleModalLabel">Add New Post</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <%= render("form", post: @post) %>
                </div>
        
              </div>
            </div>
          </div>
         <!-------------------------------------------------------------------------->
    </div>

  </div>
    
    <!--  show action ------------------------------->
    <% @posts.each do |post| %>
      <div class="card w-75 my-3">
        <div class="card-body">
          <%= render(post) %>
          <%= link_to("Show this post", post, class: "btn btn-primary") %>
        </div>
      </div>
    <% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render( "form", post: @post) %>

<br>

<div>
  <%= link_to( "Back to posts", posts_path) %>
</div>

app/views/posts/show.html.erb
<%= render(@post) %>

<div>
  <%= link_to("Edit this post", edit_post_path(@post)) %> 
  <%= link_to("Back to posts", posts_path) %> <br>
  <%= link_to("Destroy this post", @post, class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are You Sure to delete ?" }) %>
</div>

<div class="container">
  <div class="mt-3 mb-3 h6">Comments </div>
  <%= render("comments/form", post: @post, comment: @post.comments.build, submit_label: "Reply") %>
  <% @comments.each do |comment| %>
    <%= render("comments/comment", post: @post, comment: comment) %>
  <% end %>
</div>