config/routes.rb
Rails.application.routes.draw do
  root("pages#home")
  get("about", to: "pages#about")
  # posts/1/comments/3
  get("search", to: "search#index")
  resources(:posts) do
    resources :comments
  end
  get("users/profile")
  devise_for(:users, controllers: { sessions: "users/sessions", registrations: "users/registrations" })
  get("u/:id", to: "users#profile", as: "user")
end

app/views/layouts/_alerts.html.erb
<% if flash[:notice] %>
  <p class="notice text-success"><%= flash[:notice] %></p>
<% elsif flash[:error] %>
  <p class="alert text-danger"><%= flash[:error] %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg " id="navbr">
  <div class="container-fluid">
    <%= link_to("R7-BlogEngine", root_path, class: "navbar-brand h1", id: "navcol") %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="text-warning"> MENU</span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <!---------------------------Pages paths ----------------------->
        <li class="nav-item">
          <%= link_to("Posts", posts_path, class: "nav-link active text-white") %>
        </li>
        <li class="nav-item">
          <%= link_to("About", about_path, class: "nav-link text-white") %>
        </li>

      </ul>


        <ul>
          <!------Notifications ---------------------------->
          <%= render("layouts/notifications" )%>
        </ul>

           <!------Sessions Manager ----------->
              <div class="nav-item ">
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    <% if current_user %>
                      <%= current_user.name %>
                    <% else %>
                      Please Log In 
                    <% end %>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <% if user_signed_in? && current_user %>
                      <%= button_to("Log out", destroy_user_session_path, method: :delete, class: "dropdown-item") %>
                      <%= link_to("Edit Account", edit_user_registration_path, class: "dropdown-item") %>
                      <% else %>
                      <%= link_to("Sign Up", new_user_registration_path, class: "dropdown-item") %>
                      <%= link_to("Login", new_user_session_path, class: "dropdown-item") %>
                    <% end %>
                  </ul>
                </div>
              </div>
            <!---------------------------------->

        </ul>
        
        <ul>
            <!---------search bar ---------------------------->
              <%= render('search/form') %>
            <!------------------------------------------------>
        </ul>

        </ul>



    </div>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<li class="dropdown-item">
    <%= link_to(notification.to_notification.message, notification.to_notification.url) %>
</li>

app/views/layouts/_notifications.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <span class="badge rounded-pill bg-danger">
        <%= @unread.count >= 9 ? "9+" : @unread.count %> <i class="bi bi-bell fa-6x"></i>
      </span>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
      <% @unread.each do |notification| %>
        <%= render 'layouts/notification', notification: notification %>
      <% end %>
      <% if @read.count > 0 && @unread.count > 0 %>
        <li>
          <hr class="dropdown-divider">
        </li>
      <% elsif @read.count + @unread.count == 0 %>
        <li class="dropdown-item">
          No notifications yet.
        </li>
      <% end %>
      <% @read.each do |notification| %>
        <%= render 'layouts/notification', notification: notification %>
      <% end %>
    </ul>
  </li>
<% end %>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vlog7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <!----- bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    
    <%= stylesheet_link_tag("application", "data-turbo-track": "reload") %>
    <%= javascript_importmap_tags %>
     <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <header>
      <%= render("layouts/navbar") %>
    </header>

    <main>
      <div class="container">
        <%= render("layouts/alerts")%>
        <%= yield %>
      </div>
    </main>

  </body>
</html>